### ISSUE TITLE
challenge的机制有个疑问

### ISSUE THREAD

**Issue by rocqina** [chuwt/dive-into-chia#1]
farmer接收到的验证存储空间有效性的challenge，和爆块challenge有什么区别

**Comment by chuwt** [comment]
@rocqina 爆块的challenge是通过farmer接收到的challenge计算得到的，叫做sp_challenge_hash, 然后会在p盘文件中寻找适合sp_challenge_hash的答案
代码如下:
```
sp_challenge_hash = ProofOfSpace.calculate_pos_challenge(
                    plot_id,
                    new_challenge.challenge_hash,
                    new_challenge.sp_hash,
                )
proof_xs = plot_info.prover.get_full_proof(sp_challenge_hash, index)
```
其中new_chanllenge.challenge_hash 就是farmer收到的
sp_challenge_hash 是爆块的challenge

**Comment by rocqina** [comment]
![image](https://user-images.githubusercontent.com/15166591/118953166-28266980-b98f-11eb-8603-c10140f0acc2.png)
这个图里32个sigange points是不是有问题，一个sub slots应该是64个signage points

**Comment by chuwt** [comment]
是的，我之前也数了数，格子的数量不对

**Comment by rocqina** [comment]
我看协议里面，没有介绍famrer如何知道下面有多少个plots，每个plots是多少，这个不知道你有研究吗

**Comment by chuwt** [comment]
首先获取plots文件并计算答案的是harvester，harvester会通过websocket和farmer进行连接。
harvester在接收到farmer推送的new_signage_point的挑战时会定时扫描本地plots文件，然后不管有没有找到答案，都会给farmer推送一条farming_info的消息：
```
class FarmingInfo(Streamable):
    challenge_hash: bytes32
    sp_hash: bytes32
    timestamp: uint64
    passed: uint32
    proofs: uint32
    total_plots: uint32
```
其中total_plots就是harvester拥有的可用的plots数量。
但是只有plots数量，并没有k大小的标识，后面farmer收到消息会出发一个state_change方法，具体没看

**Comment by rocqina** [comment]
对，farming info只有数量，并没有每个plot的k，所以很奇怪怎么排除作假的

**Comment by chuwt** [comment]
你说的作假是指什么作假？

**Comment by rocqina** [comment]
就是区块浏览器怎么统计全网的磁盘空间多少g了，弄个假的plot是不是也会被统计到，类似下面的图
![image](https://user-images.githubusercontent.com/15166591/119286076-23ef9a00-bc76-11eb-93bd-5ace6c08fb42.png)

**Comment by chuwt** [comment]
嗯嗯，这块具体没深入了`full_node`的这个方法`get_blockchain_state`可以研究下

**Comment by rocqina** [comment]
farmer_puzzle_hash, pool_puzzle_hash,这两个怎么算出来的，感觉根私钥有关，很多地方都用到了

**Comment by chuwt** [comment]
farmer_puzzle_hash 和 pool_puzzle_hash 分别是farmer_address 和  pool_address 经过编码得来的，具体方法如下
```
def decode_puzzle_hash(address: str) -> bytes32:
    hrpgot, data = bech32_decode(address)
    if data is None:
        raise ValueError("Invalid Address")
    decoded = convertbits(data, 5, 8, False)
    decoded_bytes = bytes(decoded)
    return decoded_bytes

```

**Comment by rocqina** [comment]
好的。get_blockchain_state里面有个字段peak，我理解就是最新高度未挖出的块，这个字段你怎么理解。我在文档里看到过peak的描述
Peak: The peak of the blockchain as seen by a node is the block with the greatest weight. Weight is the sum of the difficulty of a block and all its ancestors, which is similar to height, but a shorter chain can have heavier weight, due to difficulty adjustments.
