### ISSUE TITLE
你好有问题需要请教一下！

### ISSUE THREAD

**Issue by YunL0ngLee** [chuwt/dive-into-chia#2]
关于挖矿方式：farm to poolPK 
1、如何修改多签流程才能达到效果？
2、我看代码生成presignature是由localSK签名+farmSK签名，这两点是必须的。也就是说farmSK是一定要有的，而farmSK是由主私钥派生的。但是HPOOL并没有让提供私钥，就可以挖矿，这是什么原理？
（因为没找到你的联系方式，所以在这里提个issue，多多包含，谢谢了）

**Comment by chuwt** [comment]
@YunL0ngLee
1. 因为本身是做矿池的，利益相关，所以这块暂时无法解答
2. Hpool的挖矿程序好像是自己写的，然后签名内容是我们看不见的，所以猜测他们的实现方式有2种：
- 签名中带有farmerSk, 因为farmerSk的作用只是做在挖矿中有用，对于资产是控制不了的，所以签名中可能是带有farmerSk的，后面服务端验证客户端上传的答案，如果正确，再签名，走官方流程
- 签名中不带有farmerSK，这样就要修改整个挖矿流程，起码要实现pos这块的一些逻辑，相当于客户端自己找到答案，然后签名后上传到服务器，服务器验证答案ok直接广播给节点，这种情况客户端本地是需要存在自己的私钥的

**Comment by YunL0ngLee** [comment]
> @YunL0ngLee
> 
> 1. 因为本身是做矿池的，利益相关，所以这块暂时无法解答
> 2. Hpool的挖矿程序好像是自己写的，然后签名内容是我们看不见的，所以猜测他们的实现方式有2种：
> 
> * 签名中带有farmerSk, 因为farmerSk的作用只是做在挖矿中有用，对于资产是控制不了的，所以签名中可能是带有farmerSk的，后面服务端验证客户端上传的答案，如果正确，再签名，走官方流程
> * 签名中不带有farmerSK，这样就要修改整个挖矿流程，起码要实现pos这块的一些逻辑，相当于客户端自己找到答案，然后签名后上传到服务器，服务器验证答案ok直接广播给节点，这种情况客户端本地是需要存在自己的私钥的

好的，非常感謝！
